{{- $secret := (lookup "v1" "Secret" .Release.Namespace .Values.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name | quote }}
type: Opaque
{{ if $secret -}}
data:
  auth: {{ $secret.data.auth }}
{{ else -}}
  auth: {{ htpasswd .Values.username .Values.password | b64enc | quote }}
{{ end }}