apiVersion: v1
kind: Service
metadata:
  name: { { include "mailserver.fullname" . } }
  labels: { { - include "mailserver.labels" . | nindent 4 } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: http
      protocol: TCP
      name: http
  selector: { { - include "mailserver.selectorLabels" . | nindent 4 } }
