apiVersion: v1
kind: Service
metadata:
  name: {{ include "hairpin-proxy.fullname" . }}
  labels:
    {{- include "hairpin-proxy.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  selector:
    {{- include "hairpin-proxy.selectorLabels" . | nindent 4 }}
    instance: haproxy
