{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hairpin-proxy.serviceAccountName" . }}
  labels:
    {{- include "hairpin-proxy.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "hairpin-proxy.serviceAccountName" . }}-cr
rules:
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "hairpin-proxy.serviceAccountName" . }}-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "hairpin-proxy.serviceAccountName" . }}-cr
subjects:
  - kind: ServiceAccount
    name: {{ include "hairpin-proxy.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "hairpin-proxy.serviceAccountName" . }}-r
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources:
      - configmaps
    resourceNames:
      - coredns
    verbs:
      - get
      - watch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "hairpin-proxy.serviceAccountName" . }}-rb
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "hairpin-proxy.serviceAccountName" . }}-r
subjects:
  - kind: ServiceAccount
    name: {{ include "hairpin-proxy.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
