apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "docker-mailserver.fullname" . }}
  labels: {{ - include "docker-mailserver.labels" . | nindent 4 }}
data:
  TLS_LEVEL: modern
  POSTSCREEN_ACTION: drop
  OVERRIDE_HOSTNAME: { { .Values.general.override_domain } }
  FAIL2BAN_BLOCKTYPE: drop
  POSTMASTER_ADDRESS: postmaster@{{ .Values.general.domain }}
  UPDATE_CHECK_INTERVAL: 10d
  POSTFIX_INET_PROTOCOLS: ipv4
  ONE_DIR: "1"
  DMS_DEBUG: "0"
  ENABLE_CLAMAV: "1"
  ENABLE_POSTGREY: "0"
  ENABLE_FAIL2BAN: "1"
  AMAVIS_LOGLEVEL: "-1"
  SPOOF_PROTECTION: "1"
  MOVE_SPAM_TO_JUNK: "1"
  ENABLE_UPDATE_CHECK: "1"
  ENABLE_SPAMASSASSIN: "1"
  SUPERVISOR_LOGLEVEL: warn
  SPAMASSASSIN_SPAM_TO_INBOX: "1"
  SSL_TYPE: "manual"
  SSL_CERT_PATH: "/certs/tls.crt"
  SSL_KEY_PATH: "/certs/tls.key"
  ENABLE_LDAP: "1"
  LDAP_SERVER_HOST: {{ .Values.ldap.host | quote }}
  LDAP_SEARCH_BASE: {{ .Values.ldap.search_base | quote }}
  LDAP_BIND_DN: {{ .Values.ldap.bind_dn | quote }}
  LDAP_BIND_PW: {{ .Values.ldap.bind_pwd | quote }}
  LDAP_QUERY_FILTER_DOMAIN: (|(mail=*@%s)(mailAlias=*@%s)(mailGroupMember=*@%s))
  LDAP_QUERY_FILTER_USER: (&(objectClass=inetOrgPerson)(mail=%s))
  LDAP_QUERY_FILTER_ALIAS: (&(objectClass=inetOrgPerson)(mailAlias=%s))
  LDAP_QUERY_FILTER_GROUP: (&(objectClass=inetOrgPerson)(mailGroupMember=%s))
  DOVECOT_USER_FILTER: "(&(objectClass=inetOrgPerson)(uid=%u))"
